### ISSUE TITLE
mj_loadXML error: b'Error: engine error: Could not allocate memory'

### ISSUE THREAD

**Issue by lwyncepu** [ajlangley/cpo-pytorch#5]
(cpo-pytorch-master) D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master>python train.py --model-name point_gather
train.py:32: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = load(open(config_filename, 'r'))[model_name]
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    simulator = SinglePathSimulator(env_name, policy, n_trajectories, trajectory_len)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\simulators.py", line 37, in __init__
    **env_args)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\autoassign.py", line 52, in decorated
    return f(self, *args, **kwargs)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\simulators.py", line 24, in __init__
    self.env = np.asarray([make_env(env_name, **env_args) for i in range(n_trajectories)])
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\simulators.py", line 24, in <listcomp>
    self.env = np.asarray([make_env(env_name, **env_args) for i in range(n_trajectories)])
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\simulators.py", line 16, in make_env
    return PointGatherEnv(**env_args)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\envs\point_gather.py", line 13, in __init__
    sensor_span)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\autoassign.py", line 52, in decorated
    return f(self, *args, **kwargs)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\envs\gather_env.py", line 31, in __init__
    self.model = self.build_model(model_path)
  File "D:\2021\ReinforcementLearning\cpo-pytorch-master\cpo-pytorch-master\envs\gather_env.py", line 67, in build_model
    model = load_model_from_xml(model_xml)
  File "cymj.pyx", line 147, in mujoco_py.cymj.load_model_from_xml
Exception: <mujoco model="pointmodel">
  <compiler angle="degree" coordinate="local" inertiafromgeom="true" />
  <option integrator="RK4" timestep="0.02" />
  <default>
    <joint armature="0" damping="0" limited="false" />
    <geom conaffinity="0" condim="3" density="100" friction="1 0.5 0.5" margin="0" rgba="0.8 0.6 0.4 1" />
  </default>
  <asset>
    <texture builtin="gradient" height="100" rgb1="1 1 1" rgb2="0 0 0" type="skybox" width="100" />
    <texture builtin="flat" height="1278" mark="cross" markrgb="1 1 1" name="texgeom" random="0.01" rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" type="cube" width="127" />
    <texture builtin="checker" height="100" name="texplane" rgb1="0 0 0" rgb2="0.8 0.8 0.8" type="2d" width="100" />
    <material name="MatPlane" reflectance="0.5" shininess="1" specular="1" texrepeat="30 30" texture="texplane" />
    <material name="geom" texture="texgeom" texuniform="true" />
  </asset>
  <worldbody>
    <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1" />
    <body name="torso" pos="0 0 0">
      <geom name="pointbody" pos="0 0 0.5" size="0.5" type="sphere" />
      <geom name="pointarrow" pos="0.6 0 0.5" size="0.5 0.1 0.1" type="box" />
      <joint axis="1 0 0" name="ballx" pos="0 0 0" type="slide" />
      <joint axis="0 1 0" name="bally" pos="0 0 0" type="slide" />
      <joint axis="0 0 1" limited="false" name="rot" pos="0 0 0" type="hinge" />
    </body>
  <geom conaffinity="1" condim="3" material="MatPlane" name="floor" pos="0 0 0" rgba="0.8 0.9 0.8 1" size="7.0 7.0 7.0" type="plane" /><geom conaffinity="1" condim="3" name="wall0" pos="0
 -7.0 0" rgba="0.8 0.9 0.8 1" size="7.1 0.1 1" type="box" /><geom conaffinity="1" condim="3" name="wall1" pos="0 7.0 0" rgba="0.8 0.9 0.8 1" size="7.1 0.1 1" type="box" /><geom conaffinit
y="1" condim="3" name="wall2" pos="-7.0 0 0" rgba="0.8 0.9 0.8 1" size="0.1 7.1 1" type="box" /><geom conaffinity="1" condim="3" name="wall3" pos="7.0 0 0" rgba="0.8 0.9 0.8 1" size="0.1
7.1 1" type="box" /></worldbody>
  <actuator>
    <motor ctrllimited="true" ctrlrange="-1 1" joint="ballx" />
    <motor ctrllimited="true" ctrlrange="-0.25 0.25" joint="rot" />
  </actuator>
</mujoco>
Failed to load XML from file: C:\Users\***\AppData\Local\Temp\tmpt9hpp_y5.xml. mj_loadXML error: b'Error: engine error: Could not allocate memory'

Trying to run train.py , and this bug occurs. Can anybody help me with this ?

Thanks!

**Comment by lwyncepu** [comment]
What are all the requested packages to run this code? Can anybody share?
Thanks!

**Comment by TravisCao** [comment]
Same bugs for me

**Comment by SChrisLin** [comment]
You can make `n_trajectories` small, in `config.yaml`  file, such as `10`.
